<?php
/**
 * @file
 * Provides API integration with the Twitter microblogging service.
 */

define ('TWITTER_HOST',         'http://twitter.com');
define ('TWITTER_API',          'https://api.twitter.com');
define ('TWITTER_SEARCH',       'http://twitter.com');
define ('TWITTER_TINYURL',      'http://tinyurl.com');

/**
 * Implements hook_menu().
 */
function twitter_menu() {
  $items = array();

  $items['twitter/oauth'] = array(
    'title' => 'Twitter OAuth',
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('twitter_oauth_callback'),
    'type' => MENU_CALLBACK,
    'file' => 'twitter.pages.inc',
  );

  $items['admin/settings/twitter'] = array(
    'title' => 'Twitter',
    'description' => 'Twitter accounts and settings.',
    'page callback' => 'twitter_user_settings',
    'access arguments' => array('administer twitter accounts'),
    'file' => 'twitter.pages.inc',
  );

  $items['admin/settings/twitter/default'] = array(
    'title' => 'Twitter',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/settings/twitter/settings'] = array(
    'title' => 'Settings',
    'description' => 'Twitter settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('twitter_admin_form'),
    'access arguments' => array('administer twitter'),
    'file' => 'twitter.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/%user/edit/twitter'] = array(
    'title' => 'Twitter accounts',
    'page callback' => 'twitter_user_settings',
    'page arguments' => array(1),
    'access callback' => 'twitter_account_access',
    'access arguments' => array(1),
    'weight' => 10,
    'file' => 'twitter.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_perm().
 */
function twitter_perm() {
  return array(
    'add twitter accounts',
    'add authenticated twitter accounts',
    'administer twitter',
    'administer twitter accounts',
  );
}

/**
 * Access callback for the Twitter accounts page.
 *
 * @param object $account
 *   The user account that 'owns' this Twitter accounts page.
 *
 * @return
 *   Boolean TRUE if the current user has access.
 */
function twitter_account_access($account) {
  global $user;

  // First off, verify that the current user has one of the required
  // permissions and is viewing their own user account.
  if ($user->uid == $account->uid && (user_access('add twitter accounts') || user_access('add authenticated twitter accounts'))) {
    return TRUE;
  }

  // Otherwise, verify that they have the 'administer users' permission.
  if (user_access('administer users')) {
    return TRUE;
  }

  // If neither of the above permission checks are approved, they do not have
  // permission to access this page.
  return FALSE;
}

/**
 * Implements hook_theme().
 */
function twitter_theme() {
  return array(
    'twitter_account_list_form' => array(
      'arguments' => array('form' => NULL),
    ),
    'twitter_user_accounts' => array(
      'arguments' => array('accounts' => NULL),
    ),
  );
}

/**
 * Default callback for theme('twitter_user_accounts');
 *
 * Renders a list of Twitter accounts for the user profile page.
 */
function theme_twitter_user_accounts($accounts) {
  $items = array();
  foreach ($accounts as $twitter_account) {
    $tweets = twitter_tweets($twitter_account->screen_name);
    // If we have tweets for this Twitter account, link to the View. If not, link to Twitter.
    if (count($tweets)) {
      $items[] = l('@' . $twitter_account->screen_name, 'tweets/' . $twitter_account->screen_name);
    }
    else {
      $items[] = _twitter_user_profile($twitter_account->screen_name);
    }
  }
  return theme('item_list', $items);
}

/**
 * Very lightweight helper function to generate a TinyURL for a given post.
 */
function twitter_shorten_url($url) {
  if (module_exists('shorten')) {
    return shorten_url($url);
  }
  else {
    $response = drupal_http_request(variable_get('twitter_tinyurl', TWITTER_TINYURL) . "/api-create.php?url=" . $url);
    if ($response->code == 200) {
      return $response->data;
    }
    else {
      return $url;
    }
  }
}

/**
 * Implements hook_cron().
 *
 * Imports new Twitter statuses for site users, and deletes expired tweets.
 */
function twitter_cron() {
  if (!variable_get('twitter_import', TRUE)) {
    return;
  }

  // Check if we can connect to Twitter before proceeding.
  module_load_include('inc', 'twitter');
  $twitter = twitter_connect();
  if (empty($twitter)) {
    return FALSE;
  }

  // Pull up a list of Twitter accounts that are flagged for updating,
  // sorted by how long it's been since we last updated them. This ensures
  // that the most out-of-date accounts get updated first.
  module_load_include('inc', 'twitter');
  $sql  = "SELECT twitter_uid
           FROM {twitter_account}
           WHERE uid <> 0 AND import = 1
           ORDER BY last_refresh ASC";
  $result = db_query_range($sql, 0, 20);
  try {
    while ($account = db_fetch_object($result)) {
      $twitter_account = twitter_account_load($account->twitter_uid);
      // Fetch tweets and mentions.
      twitter_fetch_user_timeline($twitter_account->id);
      if ($twitter_account->is_auth() && $twitter_account->mentions) {
        twitter_fetch_mentions_timeline($twitter_account->id);
      }
      // Mark the time this account was updated.
      db_query("UPDATE {twitter_account} SET last_refresh = %d WHERE twitter_uid=%d", $_SERVER['REQUEST_TIME'], $twitter_account->id);
    }
  } catch (TwitterException $e) {
    // The exception has already been logged so we do not need to do anything here apart from catching it.
  }

  // Nuke old statuses.
  if ($age = variable_get('twitter_expire', 0)) {
    db_query('DELETE FROM {twitter} WHERE created_time < %d', time() - $age);
  }
}


/**
 * Implementation of hook_filter().
 *
 * 0 - Twitter @username converter:
 *     Converts Twitter-style @usernames into links to Twitter account pages.
 * 1 - Twitter #hashtag converter:
 *     Converts Twitter-style #hashtags into links to hashtags.org.
 * 2 - Twitter link converter:
 *     Makes links to be opened in new pages and adds nofollow attribute.
 */
function twitter_filter($op, $delta = 0, $format = -1, $text = '') {
  switch ($op) {
    case 'list':
      return array(
        0 => t('Twitter @username converter'),
        1 => t('Twitter #hashtag converter'),
        2 => t('Twitter link converter'),
        3 => t('Embed Tweets'),
      );

    case 'description':
      switch ($delta) {
        case 0:
          return t('Converts Twitter-style @usernames into links to Twitter account pages.');
        case 1:
          return t('Converts Twitter-style #hashtags into links to twitter.com. Note: this converts all text prefixed by a "#" symbol into a hashtag link, so it can cause problems with other text.');
        case 2:
          return t('Makes links in Twitter messages to be opened in new windows and adds rel="nofollow" so these links do not penalize SEO.');
        case 3:
          return t('Converts URLs for Twitter status updates into embedded Tweets. Should be sorted after the "Limit allowed HTML tags" filter, if used.');
        default:
          return;
      }
    case 'process':
      switch ($delta) {
        case 0:
          return _twitter_filter_username($text);
        case 1:
          return _twitter_filter_hashtag($text);
        case 2:
          return _twitter_filter_link($text);
        case 3:
          return _twitter_filter_embed_tweet($text);
        default:
          return $text;
      }
    default:
      return $text;
  }
}


/**
 * Implements hook_filter_tips().
 */
function twitter_filter_tips($delta, $format, $long = FALSE) {
  global $base_url;
  switch ($delta) {
    case 0:
      return t('Twitter-style @usersnames are linked to their Twitter account pages.');
    case 1:
      return t('Twitter-style #hashtags are linked to !url.', array('!url' => '<a href="http://twitter.com/">twitter.com</a>'));
    case 2:
      return t('Twitter links within a message are opened in new tabs and have nofollo attribute.');
    case 3:
      return t('Links to Twitter status updates are converted to Embedded Tweets.');
  }
}

/**
 * Callback for twitter @username converter.
 *
 * @param string $text
 *   The text to be filtered.
 *
 * @return string
 *   The processed string.
 */
function _twitter_filter_username($text) {
  $prefix = '@';
  $destination = variable_get('twitter_host', TWITTER_HOST) . '/';
  return _twitter_filter_text($text, $prefix, $destination, 'twitter-timeline-atreply');
}

/**
 * Callback for Twitter #hashtag converter.
 *
 * @param string $text
 *   The text to be filtered.
 *
 * @return string
 *   The processed string.
 */
function _twitter_filter_hashtag($text) {
  $prefix = '#';
  $destination = variable_get('twitter_search', TWITTER_SEARCH) . '/search?q=%23';
  return _twitter_filter_text($text, $prefix, $destination, 'twitter-timeline-hashtag');
}

/**
 * Callback for twitter link converter.
 *
 * Makes links to be opened in new tabs and not to be indexed by SEO scrappers.
 *
 * @param string $text
 *   The text to be filtered.
 *
 * @return string
 *   The processed string.
 */
function _twitter_filter_link($text) {
  return str_replace('<a ', '<a target="_blank" rel="nofollow" class="twitter-timeline-link" ', $text);
}

/**
 * This helper function converts Twitter-style @usernames and #hashtags into
 * actual links.
 *
 * @param string $text
 *   The text to be filtered.
 * @param string $prefix
 *   The string to search for.
 * @param string $destination
 *   The URL that the links will point to.
 * @param string $class
 *   An optional class to insert into the link.
 *
 * @return string
 *   The processed string.
 */
function _twitter_filter_text($text, $prefix, $destination, $class = '') {
  $match = '/(?<!\w)' . preg_quote($prefix, '/') . '(\w+)/ui';
  if (!empty($class)) {
    $class = " class=\"{$class}\"";
  }
  $replacement = '<a href="' . $destination . '$1"' . $class . '>' . $prefix . '$1</a>';
  return preg_replace($match, $replacement, $text);
}

/**
 * Convert embedded URLs, hashtags and usernames in a tweet to links.
 *
 * @param string $message
 *   The tweet's text.
 * @param bool $usernames
 *   Whether or not to convert usernames to links. Defaults to TRUE.
 * @param bool $hashtags
 *   Whether or not to convert hashtags to links. Defaults to TRUE.
 * @param bool $attributes
 *   Whether or not to add extra attributes to links. Defaults to TRUE.
 * @param bool $urls
 *   Whether or not to convert other URLs to links. Defaults to TRUE.
 *
 * @return string
 *   The filtered tweet text.
 */
function twitter_filter_message($message, $usernames = TRUE, $hashtags = TRUE, $attributes = TRUE, $urls = TRUE) {
  // Link usernames with their profiles.
  if ($usernames) {
    $message = _twitter_filter_username($message);
  }

  // Link hashtags.
  if ($hashtags) {
    $message = _twitter_filter_hashtag($message);
  }

  // Add extra attributes to links.
  if ($attributes) {
    $message = _twitter_filter_link($message);
  }

  // Standard URLs.
  if ($urls) {
    $message = _filter_url($message, FILTER_DEFAULT);
  }

  // Avoid XSS within the message.
  return filter_xss($message);
}

/**
 * Callback for Embedded Tweets.
 */
function _twitter_filter_embed_tweet($text) {
  module_load_include('inc', 'twitter');

  // Tags to skip and not recurse into.
  $ignore_tags = 'a|script|style|code|pre';

  // Split at all tags; ensures that no tags or attributes are processed.
  $chunks = preg_split('/(<.+?>)/is', $text, -1, PREG_SPLIT_DELIM_CAPTURE);

  // PHP ensures that the array consists of alternating delimiters and
  // literals, and begins and ends with a literal (inserting NULL as required).
  // Therefore, the first chunk is always text:
  $chunk_type = 'text';

  // If a tag of $ignore_tags is found, it is stored in $open_tag and only
  // removed when the closing tag is found. Until the closing tag is found, no
  // replacements are made.
  $open_tag = '';

  foreach ($chunks as $i => $chunk) {
    if ($chunk_type == 'text') {
      // Only process this text if there are no unclosed $ignore_tags.
      if ($open_tag == '') {
        // Check for links to Tweets to replace with embed code.
        $tweets = array();
        preg_match_all('/https?:\/\/(www\.)?twitter.com\/.+?\/status(es)?\/(.*)/i', $chunks[$i], $tweets, PREG_SET_ORDER);
        foreach ($tweets as $tweet) {
          $url = $tweet[0];
          $id = $tweet[3];
          $embed = twitter_statuses_oembed($id);
          $chunks[$i] = str_replace($url, $embed['html'], $chunks[$i]);
        }
      }
      // Text chunk is done, so next chunk must be a tag.
      $chunk_type = 'tag';
    }
    else {
      // Only process this tag if there are no unclosed $ignore_tags.
      if ($open_tag == '') {
        // Check whether this tag is contained in $ignore_tags.
        if (preg_match("`<($ignore_tags)(?:\s|>)`i", $chunks[$i], $matches)) {
          $open_tag = $matches[1];
        }
      }
      // Otherwise, check whether this is the closing tag for $open_tag.
      else {
        if (preg_match("`<\/$open_tag>`i", $chunks[$i], $matches)) {
          $open_tag = '';
        }
      }
      // Tag chunk is done, so next chunk must be text.
      $chunk_type = 'text';
    }
  }
  return implode($chunks);
}

/**
 * Implements hook_views_api().
 */
function twitter_views_api() {
  return array('api' => 2);
}

/**
 * Implements hook_user().
 */
function twitter_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'load':
      $account->twitter_accounts = module_invoke_all('twitter_accounts', $account);
      break;
    case 'delete':
      foreach ($account->twitter_accounts as $twitter_account) {
        twitter_account_delete($twitter_account->id);
      }
      break;
    case 'view':
      if (!empty($account->twitter_accounts)) {
        $account->content['summary']['twitter'] = array(
          '#title' => t('Twitter accounts'),
          '#type' => 'user_profile_item',
          '#weight' => 10,
          '#value' => theme('twitter_user_accounts', $account->twitter_accounts),
        );
      }
      break;
  }
}

/**
 * Implements hook_twitter_accounts().
 *
 * @return array
 *   All Twitter accounts for this user; the anonymous user will return an
 *   empty array.
 */
function twitter_twitter_accounts($account) {
  if ($account->uid == 0) {
    return array();
  }

  module_load_include('inc', 'twitter');

  $twitter_accounts = array();

  $sql = "SELECT twitter_uid FROM {twitter_account} WHERE uid = %d";
  $results = db_query($sql, $account->uid);

  while ($row = db_fetch_array($results)) {
    $key = $row['twitter_uid'];
    $twitter_accounts[] = twitter_account_load($key);
  }
  return $twitter_accounts;
}

/**
 * Checks if the Twitter Application keys are set.
 *
 * @return
 *   boolean TRUE if both the Twitter Application key and secret are set.
 */
function twitter_api_keys() {
  $key = variable_get('twitter_consumer_key', NULL);
  $secret = variable_get('twitter_consumer_secret', NULL);
  return !(empty($key) && empty($secret));
}

/**
 * Helper to build a Twitter profile URL
 */
function _twitter_user_profile($screen_name) {
  return l('@' . $screen_name, TWITTER_HOST . '/' . $screen_name);
}

/**
 * Helper to build a Twitter status URL.
 *
 * @param object $status
 *   A TwitterStatus object.
 */
function _twitter_status_url($status) {
  return TWITTER_HOST . '/' . $status->user->screen_name . '/status/' . $status->id;
}
